<?php

/**
 * @file
 * The varbase_heroslider_media.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function varbase_heroslider_media_theme() {
  return [
    'node__varbase_heroslider_media' => [
      'template' => 'node--varbase-heroslider-media',
      'base hook' => 'node'
    ],
  ];
}
