<?php

/**
 * @file
 * The varbase_heroslider_media.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function varbase_heroslider_media_theme() {
  return [
    'node__varbase_heroslider_media' => [
      'template' => 'node--varbase-heroslider-media',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function varbase_heroslider_media_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {

  if ($hook == 'media_oembed_iframe') {
    if (isset($variables['provider_name'])) {
        $suggestions[] = 'media-oembed-iframe--heroslider';
        $suggestions[] = 'media-oembed-iframe--heroslider--remote-video--provider--' . $variables['provider_name'];
    }
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function varbase_heroslider_media_theme_registry_alter(&$theme_registry) {

  if (isset($theme_registry['media_oembed_iframe'])) {
    $theme_registry['media_oembed_iframe']['path'] = drupal_get_path('module', 'varbase_heroslider_media') . '/templates';
    $theme_registry['media_oembed_iframe']['template'] = 'media-oembed-iframe--heroslider';
    $theme_registry['media_oembed_iframe']['theme path'] = \Drupal::service('module_handler')->getModule("varbase_heroslider_media")->getPath();
    $theme_registry['media_oembed_iframe']['variables']['module_handler_path'] = \Drupal::service('module_handler')->getModule("varbase_heroslider_media")->getPath();
    $theme_registry['media_oembed_iframe']['variables']['theme_handler_path'] = \Drupal::theme()->getActiveTheme()->getPath();
    $theme_registry['media_oembed_iframe']['variables']['base_path'] = base_path();
  }
}
